---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-prod-db-pvc
  labels:
    username: ianwood
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
