---
apiVersion: v1
kind: Service
metadata:
  name: app-prod-db-service
  labels:
    username: ianwood
    env: prod
spec:
  type: ClusterIP
  selector:
    app: app-prod-db-deployment
  ports:
  - name: app-prod-db-service-rport
    port: 6379
    targetPort: 6379
