---
apiVersion: v1
kind: Service
metadata:
  name: app-prod-api-service
  labels:
    username: ianwood
    env: prod
spec:
  type: ClusterIP
  selector:
    app: app-prod-api-deployment
  ports:
  - name: app-prod-api-service-fport
    port: 5000
    targetPort: 5000
